### ISSUE TITLE
Cannot load Skill

### ISSUE THREAD

**Issue by glor** [normandmickey/skill-internet-radio#14]
From the error log:
```
10:50:31.655 - mycroft.skills.core:load_skill:169 - ERROR - Failed to load skill: skill-internet-radio.normandmickey
Traceback (most recent call last):
  File "/home/glor/git/mycroft-core/mycroft/skills/core.py", line 149, in load_skill
    raise e
  File "/home/glor/git/mycroft-core/mycroft/skills/core.py", line 145, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/skill-internet-radio.normandmickey/__init__.py", line 157, in initialize
    self.audioservice = AudioService(self.emitter)
AttributeError: 'InternetRadioSkill' object has no attribute 'emitter'
```

**Comment by JedidiahStolzfus** [comment]
I fixed this by changing line 157:
self.audioservice = AudioService(self.bus)
